channels:
- conda-forge
dependencies:
- python=3.11.3
- pip<=22.3.1
- pip:
  - mlflow==2.21.3
  - accelerate==1.5.2
  - astunparse==1.6.3
  - attrs==23.1.0
  - cffi==1.15.1
  - defusedxml==0.7.1
  - dill==0.3.8
  - etils==1.5.0
  - googleapis-common-protos==1.70.0
  - importlib-resources==6.1.0
  - jax==0.4.16
  - jaxlib==0.4.16
  - numpy==1.24.4
  - optree==0.14.0
  - pandas==2.2.3
  - rich==13.4.2
  - scikit-learn==1.5.2
  - scipy==1.10.1
  - sentencepiece==0.2.0
  - torch==2.2.0
  - torchvision==0.15.2
  - transformers==4.30.0
  - uuid==1.30
  - zstandard==0.23.0
name: mlflow-env
