"""removed branch from department

Revision ID: 758e978340de
Revises: 36eaa46da7b1
Create Date: 2025-04-18 17:55:44.900739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758e978340de'
down_revision = '36eaa46da7b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_column('branch')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
